classdef Config < handle
  %CONFIG Summary of this class goes here
  %   Detailed explanation goes here
  
  properties
    modal;
    flag;
    callback;
    analyzed = 1;
    vel_norm = 0;
    vel_qrs  = 0;
    amp_norm = 0;
  end
  
  methods
        
    function setCallback(self, x)
      self.callback = x;
    end
    
    function show(self)
%     function show(self)
      self.modal = dialog('Units', 'normalized',...
        'Position',[.375 .225 .25 .55],...
        'Name','Tresholds settings',...
        'DeleteFcn', @self.beingremove);
      uicontrol(self.modal, 'Style', 'text',...
        'FontSize', 15,...
        'String', 'Insert tresholds values in fields',...
        'Units', 'normalized',...
        'Position', [.3, .8, .4, .1]);
      
      
      self.vel_norm = uicontrol(self.modal, 'Style', 'edit',...
        'String', num2str(self.vel_norm),...
        'Units', 'normalized',...
        'Position', [.2, .7, .07, .03]);
      uicontrol(self.modal, 'Style', 'text',...
        'String', 'Insert value for slope in standard areas',...
        'Units', 'normalized',...
        'Position', [.3, .7, .4, .03]);
      self.vel_qrs = uicontrol(self.modal, 'Style', 'edit',...
        'String', num2str(self.vel_qrs),...
        'Units', 'normalized',...
        'Position', [.2, .6, .07, .03]);
      uicontrol(self.modal, 'Style', 'text',...
        'String', 'Insert value for slope in QRS areas',...
        'Units', 'normalized',...
        'Position', [.3, .6, .4, .03]);
      self.amp_norm = uicontrol(self.modal, 'Style', 'edit',...
        'String', num2str(self.amp_norm),...
        'Units', 'normalized',...
        'Position', [.2, .5, .07, .03]);
      uicontrol(self.modal, 'Style', 'text',...
        'String', 'Insert value for overall amplitude',...
        'Units', 'normalized',...
        'Position', [.3, .5, .4, .03]);
      
      self.flag = uicontrol(self.modal, 'Style', 'checkbox',...
        'String', 'Analyse all channels', 'value', self.analyzed,...
        'Units', 'normalized', 'Position', [.2, .1, .3, .04]);
      
      uicontrol(self.modal, 'String', 'OK', 'Units', 'normalized',...
        'Position', [.52, .1, .11, .04],...
        'Selected', 'on',...
        'Callback', @self.analyse_callback) % analyse
      uicontrol(self.modal,'String', 'Cancel', 'Units', 'normalized',...
        'Position', [.64, .1, .11, .04],...
        'Callback', @(~,~) delete(self.modal)); % cancel
    end
    
    function setValues(self, varargin)
      p = inputParser;
      p.addParameter('SlopeTreshold', 0, @isnumeric);
      p.addParameter('AmpTreshold'  , 0, @isnumeric);
      p.addParameter('QrsTreshold'  , 0, @isnumeric);
      p.parse(varargin{:});
      
      self.vel_norm = p.Results.SlopeTreshold;
      self.amp_norm = p.Results.AmpTreshold;
      self.vel_qrs  = p.Results.QrsTreshold;
    end
  end
  
  methods (Access=private)
    function analyse_callback(self, ~, ~)
      % call analyse function with tresholds
      delete(self.modal);
      self.callback(self.flag);
    end
    
    function beingremove(self, ~, ~)
      self.vel_norm = str2double(self.vel_norm.String);
      self.vel_qrs  = str2double(self.vel_qrs.String);
      self.amp_norm = str2double(self.amp_norm.String);
      self.flag     = self.flag.Value;
      self.analyzed = 0;
      delete(self.modal);
    end
  end
  
end
